retrain:
    flag: True
    model:
      backbone:
        conv_stem: [1, 2, 3, 32, [1], False, ['conv3x3']]

        stage1_1: [1, 1, 32, 16, [1], False, ['ir_5x5_se']]

        stage2_1: [1, 2, 16, 32, [6], False, ['ir_5x5_se']]

        stage3_1: [1, 2, 32, 40, [6], False, ['ir_7x7_se']]
        stage3_2: [1, 1, 40, 40, [6], False, ['ir_7x7_se']]
        stage3_3: [1, 1, 40, 40, [6], False, ['ir_5x5_se']]
        stage3_4: [1, 1, 40, 40, [6], False, ['ir_3x3_se']]

        stage4_1: [1, 2, 40, 80, [6], False, ['ir_5x5_se']]
        stage4_2: [1, 1, 80, 80, [6], False, ['ir_5x5_se']]

        stage5_1: [1, 1, 80, 96, [6], False, ['ir_7x7_se']]
        stage5_2: [1, 1, 96, 96, [6], False, ['ir_7x7_se']]

        stage6_1: [1, 2, 96, 192, [6], False, ['ir_7x7_se']]
        stage6_2: [1, 1, 192, 192, [6], False, ['ir_5x5_se']]
        stage6_3: [1, 1, 192, 192, [6], False, ['ir_7x7_se']]

        stage7_1: [1, 1, 192, 320, [6], False, ['ir_5x5_se']]

        conv_out: [1, 1, 320, 1280, [1], False, ['conv2d']] 
        final_pooling: True
      head:
        linear1:
          dim_in: 1280
          dim_out: 1000
      loss_type: 's-softmax'

      # depth_multiplier: [[1.00], # scaling stage 0
      #                      [1.04, 1.08, 1.12, 1.16], # scaling stage 1
      #                      [1.20, 1.24, 1.28, 1.32, 1.36], # scaling stage 2
      #                      [1.40, 1.44, 1.48, 1.52, 1.56, 1.60, 1.64]] # scaling stage 3
      # channel_multiplier: [[1.00], # scaling stage 0
      #                        [1.04, 1.08, 1.12, 1.16], # scaling stage 1
      #                        [1.20, 1.24, 1.28, 1.32, 1.36], # scaling stage 2
      #                        [1.40, 1.44, 1.48, 1.52, 1.56, 1.60, 1.64]] # scaling stage 3
      # resolution_multiplier: [[224],
      #                         [224, 240, 256], 
      #                         [272, 288, 304], 
      #                         [320, 336, 354]]
      # [[1.], [1., 1.07, 1.14], [1.21, 1.285, 1.355], [1.425, 1.5, 1.58]]
      scaling:
        depth: 1.848
        width: 1.688
        resolution: 2.378
        stage: 1.

